### ISSUE TITLE
The Demo for LSTM on Phenotyping Prediction with GPU

### ISSUE THREAD

**Issue by liuxiaoliXRZS** [yzhao062/PyHealth#11]
`
cur_dataset = expdata_generator(exp_id=exp_id)
`
should change to
`
cur_dataset = expdata_generator(expdata_id=expdata_id)
`
Thanks~

**Comment by qxiaobu** [comment]
Thanks very much. We have  updated

**Comment by qxiaobu** [comment]
Thanks very much. We have updated

> `cur_dataset = expdata_generator(exp_id=exp_id)`
> should change to
> `cur_dataset = expdata_generator(expdata_id=expdata_id)`
> Thanks~
